# Generated by Django 5.0.4 on 2024-05-10 15:46

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("name", models.CharField(max_length=50)),
                (
                    "vendor_code",
                    models.CharField(
                        default=api.models.get_vendor_code,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_details", models.TextField(max_length=10)),
                ("address", models.TextField(default="user address")),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("po_number", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateTimeField(null=True)),
                ("delivery_date", models.DateTimeField()),
                ("items", models.JSONField(default=dict)),
                ("quantity", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("completed", "completed"),
                            ("canceled", "canceled"),
                        ],
                        default="pending",
                        max_length=9,
                    ),
                ),
                ("quality_rating", models.FloatField(null=True)),
                ("issue_date", models.DateTimeField(auto_now_add=True)),
                ("acknowledgement_date", models.DateTimeField(null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.vendor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("on_time_delivery_rate", models.FloatField(default=0)),
                ("quality_rating_avg", models.FloatField(default=0)),
                ("average_response_time", models.FloatField(default=0)),
                ("fulfillment_rate", models.FloatField(default=0)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.vendor"
                    ),
                ),
            ],
        ),
    ]
