# Generated by Django 5.0.4 on 2024-05-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="average_response_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="fulfillment_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="on_time_delivery_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="quality_rating_avg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="acknowledgement_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="quality_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
